name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04  # Or ubuntu-22.04, depending on compatibility

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV
        id: nvm

      - name: Set the correct Node version using nvm (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NVMRC }}"
          
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build --verbose
        env:
          CI: false
      
      - name: Copy CSS into build
        run: |
          mkdir -p ./build/assets/css
          mkdir -p ./build/assets/css/colors
          cp ./src/assets/css/style.css ./build/assets/css
          cp ./src/assets/css/colors/default.css ./build/assets/css/colors
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Sync with AWS S3 Bucket
        run: aws s3 sync ./build s3://stockpitch.texasusit.org --debug
